name: Ubuntu/Guile 3.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install \
              autoconf \
              automake \
              guile-3.0 \
              guile-3.0-dev \
              guile-json \

      - uses: actions/checkout@v2

      - run: autoreconf -fiv .

      - run: ./configure

      - run: make -j$(nproc)
